CREATE TABLE IF NOT EXISTS `SynomasterProgress` (
  `id` VARCHAR(36) NOT NULL,
  `mode` VARCHAR(255) NOT NULL,
  `currentIndex` INT NOT NULL DEFAULT 0,
  `totalItems` INT NOT NULL DEFAULT 0,
  `completedCount` INT NOT NULL DEFAULT 0,
  `lastPracticedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mode` (`mode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
